### ISSUE TITLE
在HBuilderX 中通过微信开发者工具运行，首页 page/index/index 加载白屏

### ISSUE THREAD

**Issue by wxsolo** [marsgis/mars3d-uni-app#2]
HBuilderX 版本： 3.4.15.20220610
微信开发者工具版本：1.06.2206090
[JS 文件编译错误] 以下文件体积超过 500KB，已跳过压缩以及 ES6 转 ES5 的处理。
static/lib/Cesium/Cesium.js
static/lib/mars3d/mars3d.js

**Comment by muyao1987** [comment]
目前尚未找到具体原因, 目前如需将本项目运行到app平台，请先打包为静态资源后使用HbuilderX打包，或者使用webview。

如果您有解决方法，欢迎提交pull 或 发代码到我邮箱wh@marsgis.cn

**Comment by muyao1987** [comment]
可能的方式： 需要改下lib.5plus.base-release.aar 基座代码，在WebviewActivity.java 中设置webView时加下允许跨域

**Comment by muyao1987** [comment]
目前已修复，可以下载最新代码
