### ISSUE TITLE
可以使用npm安装包那种方式使用吗 vite-plugin-cesium

### ISSUE THREAD

**Issue by mimimiaomiao1** [marsgis/mars3d-uni-app#5]
npm 安装这个 vite-plugin-cesium

**Comment by muyao1987** [comment]
## vite-plugin-mars3d使用说明

### 安装

```sh
//安装mars3d主库
npm install mars3d mars3d-cesium @turf/turf --save

//安装vite插件
npm install vite-plugin-mars3d --save
```


### 配置

> vite.config.ts中引入plugin插件

```js
import { defineConfig } from 'vite';
import { mars3dPlugin } from 'vite-plugin-mars3d';

export default defineConfig({
  plugins: [mars3dPlugin()]
});
```

> 如果你个性化需求，也可以按需传入参数

```js
import { defineConfig } from 'vite';
import { mars3dPlugin } from 'vite-plugin-mars3d';

export default defineConfig({
  plugins: [
      mars3dPlugin({
        mars3dPackageName: "mars3d",
        mars3dRunPath: "mars3d",//目录名称
        cesiumPackageName: "mars3d-cesium",
        cesiumRunPath: "mars3d-cesium",//目录名称
        useStatic: false,
        useCDN: false
      }),
  ]
});
```


### 使用原生cesium时
1. 不要安装`mars3d-cesium`包，仅安装`cesium`包，就是不能同时存在2个`cesium`包
package.json文件示例:
```json
  "dependencies": {
    "cesium": "^1.118.0",
    "mars3d": "^3.7.19",
    "mars3d-space": "^3.7.19",
    "rollup": "^2.79.1",
    "vue": "^3.2.47"
  },
  "devDependencies": {
    "vite": "^4.2.0",
    "vite-plugin-mars3d": "^4.1.0",
    "@vitejs/plugin-vue": "^4.1.0",
    "typescript": "^4.9.3",
    "vue-tsc": "^1.2.0"
  }
```

2. vite.config中引入时使用配置 `mars3dPlugin({ cesiumPackageName: "cesium" })`

vite.config.ts文件示例:
```js
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import { mars3dPlugin } from "vite-plugin-mars3d"; // 引入插件


export default defineConfig({
  plugins: [
    vue(),
    mars3dPlugin({ cesiumPackageName: "cesium" }), // 使用cesium原生包
  ],
});
```


### 常见问题
- 如果项目的 package.json 没有 type:"module" ，请使用  "vite-plugin-mars3d":"~3.1.3"
- 如果项目的 package.json 有 type:"module" 直接用最新版本即可。

**Comment by mimimiaomiao1** [comment]
> ## vite-plugin-mars3d使用说明
> ### 安装
> ```shell
> //安装mars3d主库
> npm install mars3d mars3d-cesium @turf/turf --save
> 
> //安装vite插件
> npm install vite-plugin-mars3d --save
> ```
> 
> ### 配置
> > vite.config.ts中引入plugin插件
> 
> ```js
> import { defineConfig } from 'vite';
> import { mars3dPlugin } from 'vite-plugin-mars3d';
> 
> export default defineConfig({
>   plugins: [mars3dPlugin()]
> });
> ```
> 
> > 如果你个性化需求，也可以按需传入参数
> 
> ```js
> import { defineConfig } from 'vite';
> import { mars3dPlugin } from 'vite-plugin-mars3d';
> 
> export default defineConfig({
>   plugins: [
>       mars3dPlugin({
>         mars3dPackageName: "mars3d",
>         mars3dRunPath: "mars3d",//目录名称
>         cesiumPackageName: "mars3d-cesium",
>         cesiumRunPath: "mars3d-cesium",//目录名称
>         useStatic: false,
>         useCDN: false
>       }),
>   ]
> });
> ```
> 
> ### 使用原生cesium时
> 1. 不要安装`mars3d-cesium`包，仅安装`cesium`包，就是不能同时存在2个`cesium`包
>    package.json文件示例:
> 
> ```json
>   "dependencies": {
>     "cesium": "^1.118.0",
>     "mars3d": "^3.7.19",
>     "mars3d-space": "^3.7.19",
>     "rollup": "^2.79.1",
>     "vue": "^3.2.47"
>   },
>   "devDependencies": {
>     "vite": "^4.2.0",
>     "vite-plugin-mars3d": "^4.1.0",
>     "@vitejs/plugin-vue": "^4.1.0",
>     "typescript": "^4.9.3",
>     "vue-tsc": "^1.2.0"
>   }
> ```
> 
> 2. vite.config中引入时使用配置 `mars3dPlugin({ cesiumPackageName: "cesium" })`
> 
> vite.config.ts文件示例:
> 
> ```js
> import { defineConfig } from "vite";
> import vue from "@vitejs/plugin-vue";
> import { mars3dPlugin } from "vite-plugin-mars3d"; // 引入插件
> 
> 
> export default defineConfig({
>   plugins: [
>     vue(),
>     mars3dPlugin({ cesiumPackageName: "cesium" }), // 使用cesium原生包
>   ],
> });
> ```
> 
> ### 常见问题
> * 如果项目的 package.json 没有 type:"module" ，请使用  "vite-plugin-mars3d":"~3.1.3"
> * 如果项目的 package.json 有 type:"module" 直接用最新版本即可。

请问这个要花钱吗？

**Comment by muyao1987** [comment]
免费无限制使用
